[CARBONDATA-4336] Table Status Versioning
apache/carbondata pull request #4261
Opened 2022-04-22 13:32 UTC by Indhumathi27

### Why is this PR needed?

Currently, carbondata will store the records of a transaction (load/insert/IUD/Add/drop segment) in a metadata file named `tablestatus’ which will be present in the Metadata directory. If the tablestatus file is lost, then the metadata for the transactions cannot be recovered directly, as there is no previous version file available for tablestatus. Hence, if we support versioning for tablestatus files, then it will be easy to recover the current version tablestatus meta from previous version tablestatus files.

Please refer [Table Status Versioning & Recovery Tool](https://docs.google.com/document/d/13YzVliFESV8ExAxUXfx-Dk9DYTaUGi-6PhCqTZdFZyQ/edit?usp=sharing) for more info.
 
 ### What changes were proposed in this PR?
-> On each transaction commit, committed the latest load metadata details to a new version file
-> Updated the latest tablestatus version timestamp in the table properties [CarbonTable cache] and in the hive metastore
-> Added a table status version tool which can recover the latest transaction details based on old version file
    
 ### Does this PR introduce any user interface change?
 - Yes

 ### Is any new testcase added?
 - Yes

2022-04-22 14:16 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6279/

2022-04-22 19:40 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/669/

2022-04-22 21:14 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4535/

2022-04-22 22:02 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/670/

2022-04-25 20:54 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4536/

2022-04-25 20:54 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6281/

2022-04-25 21:12 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/671/

2022-04-26 05:46 UTC, Indhumathi27 commented
retest this please

2022-04-26 06:29 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/672/

2022-04-26 06:39 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6282/

2022-04-26 06:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4537/

2022-04-26 06:53 UTC, AlphaAyush commented
retest this please

2022-04-26 07:42 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4538/

2022-04-26 08:22 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6283/

2022-04-26 09:01 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/673/

2022-04-26 13:33 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4540/

2022-04-26 13:34 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6285/

2022-04-26 21:19 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6286/

2022-04-26 21:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/676/

2022-04-27 12:11 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6288/

2022-04-27 12:16 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4543/

2022-04-27 12:18 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/678/

2022-04-27 19:12 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6290/

2022-04-27 19:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/680/

2022-04-28 16:21 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6291/

2022-04-28 16:55 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/681/

2022-04-28 16:57 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4546/

2022-04-29 13:22 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4547/

2022-04-29 15:30 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6292/

2022-05-04 11:54 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6293/

2022-05-04 12:26 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/683/

2022-05-04 12:28 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4548/

2022-05-04 14:37 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4549/

2022-05-04 14:38 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6294/

2022-05-04 16:55 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/684/

2022-05-05 10:02 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4550/

2022-05-05 10:12 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6295/

2022-05-05 10:36 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/685/

2022-05-05 23:03 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6296/

2022-05-05 23:13 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4551/

2022-05-05 23:40 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/686/

2022-05-06 18:18 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6297/

2022-05-06 18:49 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4552/

2022-05-06 19:28 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/687/

2022-05-11 23:09 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6301/

2022-05-11 23:09 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4556/

2022-05-11 23:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/691/

2022-05-13 01:37 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4557/

2022-05-13 01:39 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6302/

2022-05-13 02:05 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/692/

2022-05-13 21:09 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6303/

2022-05-13 21:13 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4558/

2022-05-13 21:48 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/693/

2022-05-16 05:35 UTC, Indhumathi27 commented
retest this please

2022-05-16 08:19 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6304/

2022-05-16 08:43 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/694/

2022-05-16 14:55 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/695/

2022-05-17 05:28 UTC, akashrn5 commented
@Indhumathi27 as discussed and mentioned in design also, the recovery is possible only if the latest table status file is missing. if any in between files get missed, then we cannot recover it. But existing solution suggest that, if the query gives empty results user has to recover the latest table status file. But valid query can also give empty results, so we should not depend on this scenario only.

So, if table status file goes missing, then any next table level operation should be able to throw exception for missing file and either user should recover or auto recover should be triggered. If auto is not yet supported, then we can do that later, now user can do it manually.

2022-05-17 12:59 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6314/

2022-05-17 13:27 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/703/

2022-05-17 19:31 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6315/

2022-05-17 19:33 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4570/

2022-05-18 13:16 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4571/

2022-05-18 14:35 UTC, Indhumathi27 commented
retest this please

2022-05-18 16:36 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6316/

2022-05-18 16:47 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/705/

2022-05-18 21:42 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4572/

2022-05-18 21:42 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6317/

2022-05-19 08:58 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6318/

2022-05-19 10:57 UTC, CarbonDataQA2 commented
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4573/

2022-05-19 11:22 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/706/

2022-05-19 14:39 UTC, Indhumathi27 commented
retest this please

2022-05-19 17:32 UTC, CarbonDataQA2 commented
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6319/

2022-05-19 17:36 UTC, CarbonDataQA2 commented
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4574/

2022-05-19 18:03 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/707/

2022-05-20 07:00 UTC, kunal642 requested changes

2022-05-20 10:06 UTC, Indhumathi27 commented on core/src/main/java/org/apache/carbondata/core/statusmanager/SegmentStatusManager.java
> +          if (ex.getMessage().contains("Table Status Version file")) {
if version file does not exist, after retry we have to check and throw exception

2022-05-20 16:04 UTC, Indhumathi27 commented on core/src/main/java/org/apache/carbondata/core/metadata/SegmentFileStore.java
> +        new SegmentStatusManager(absoluteTableIdentifier, carbonTable.getTableStatusVersion());
carbonTable.getTableStatusVersion() is the read version and tblStatusVersion is the new version for writing

2022-05-20 20:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/708/

2022-05-20 20:43 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6320/

2022-05-20 21:11 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4575/

2022-05-23 04:55 UTC, Indhumathi27 commented
retest this please

2022-05-23 11:51 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6323/

2022-05-23 13:47 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6324/

2022-05-23 13:56 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/712/

2022-05-25 03:21 UTC, Indhumathi27 commented
retest this please

2022-05-25 04:33 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4581/

2022-05-25 04:35 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6326/

2022-05-25 04:45 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/714/

2022-05-25 15:33 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4584/

2022-05-25 16:04 UTC, CarbonDataQA2 commented
Build Failed  with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/717/

2022-05-25 18:05 UTC, Indhumathi27 commented
retest this please

2022-05-25 22:16 UTC, CarbonDataQA2 commented
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/718/

2022-05-26 01:50 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6330/

2022-05-26 01:50 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4585/

2022-05-26 08:15 UTC, Indhumathi27 commented
retest this please

2022-05-26 08:18 UTC, Indhumathi27 commented
retest this please

2022-05-26 10:41 UTC, CarbonDataQA2 commented
Build Failed  with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6331/

2022-05-26 10:52 UTC, CarbonDataQA2 commented
Build Success with Spark 2.4.5, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_2.4.5/4586/

2022-05-26 11:18 UTC, CarbonDataQA2 commented
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/719/

2022-05-26 12:29 UTC, Indhumathi27 commented
retest this please

2022-05-26 17:17 UTC, CarbonDataQA2 commented
Build Success with Spark 2.3.4, Please check CI http://121.244.95.60:12602/job/ApacheCarbonPRBuilder2.3/6332/

2022-05-26 17:55 UTC, CarbonDataQA2 commented
Build Success with Spark 3.1, Please check CI http://121.244.95.60:12602/job/ApacheCarbon_PR_Builder_3.1/720/

2022-05-27 05:42 UTC, Indhumathi27 commented
@kunal642 @akashrn5 please review

2022-05-27 06:03 UTC, kunal642 commented
LGTM

2022-05-27 06:06 UTC, akashrn5 commented
LGTM

2022-05-27 06:16 UTC, closed without merging